# Change these first
owner: ai4up # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: EUBUCCO
    url: https://eubucco.com
  - name: Cities Explorer
    url: https://cities-explorer.eubucco.com

status-website:
  # Remove the `cname` line if you don't have a custom domain and use `baseUrl`
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: EUBUCCO Status
  introTitle: "**EUBUCCO Status**"
  introMessage: Real-time uptime and response-time monitoring for EUBUCCO services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
